### ISSUE TITLE
Idle nulls

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/e-trace-encap#11]
> A null packet is inserted in the data stream when there are no normal encapsulated packets to send.

Can this be null.idle or null.alignment? Or it must be null.idle?

**Comment by IainCRobertson** [comment]
My expectation is that it would be null.idle, but strictly it could be either, and the text doesn't disallow this.  I can clarify if you'd like.

**Comment by ved-rivos** [comment]
If such optionality is not useful in providing meaningful benefits to the implementation then it would be good to state null.idle for maximal compatibility.

**Comment by IainCRobertson** [comment]
Actually, the spec is already clear on this - see the synchronization rules at the end of section 2.3.  This is explicit that all but the final null must be null.idle.  I don't think any changes are required for this.

**Comment by ved-rivos** [comment]
While section 2.3 talks about generating synchronization sequences, the section 2.2 indicates that null packets should be inserted when there are no normal encapsulated packets to send. Should the section 2.2 last sentence instead say "A synchronization sequence should be inserted in the data stream when there are no normal encapsulated packets to send."? However, if section 2.2 is not talking about synchronization sequences that would be inserted periodically even when normal encapsulated packets are available to send, then 2.2 is a distinct scenario than synchronization and would benefit from stating "A null.idle packet is..."

**Comment by IainCRobertson** [comment]
I see your point.  Your suggestion for the last sentence  doesn't work, as a synchronization sequence has a minimum length, and you might only be idle for a couple of cycles.  

I think the solution is to add a list of rules here too.  These are similar to sync rules, but without the length restrictions:

An idle sequence has a length of M+1 bytes (M >=0), comprising:
 - for unframed data streams, M consecutive null.idle packets directly followed by one null.alignment packet;
 - for framed data streams, M consecutive null.idle packets, directly follwed by one null.idle or null.alignment packet

Actually then we can replace the rules in the sync section, by referring to the above rules and saying a sync sequence complies with these rules but additionally has M >= N.

As there's already an MR for Issue 5 that has edits to this text, I'll wait for that MR to be approved before submitting another, to avoid conflicts.

**Comment by ved-rivos** [comment]
My last sentence was suggesting that the idle sequence is just 1 or more null.idle packets i.e., the existing sentence in section 2.2 be retained with the only change to replace "null" by "null.idle".  

This proposal also works, except it would require an idle sequence to be at least 2 null packets. Requiring each idling to consume two slots may be okay but seems was not really necessary.

**Comment by IainCRobertson** [comment]
No, M can be 0, so minimum value of M+1 is 1.  I'll work up a PR after #5 is merged

**Comment by ved-rivos** [comment]
I am not sure how an implementation can predict that the idle slot is the last idle slot and there will be something valid to send in next slot. So requiring that a null.idle must be followed by a null.alignment forces inserting an alignment null. Hence my concern that the requirement that idle sequences end in null.alignment will force implementations to insert a gratuitous null.alignment if they dont have premonition about the current idle being the last idle.

**Comment by IainCRobertson** [comment]
In my experience this isn't an issue.  For a start, null.alignment is only mandatory if the data stream is not byte-aligned.  Generally speaking, this is only going to be the case at a low-speed off-chip interface (e.g. PIB).  At the sink there is usually a buffer and/or gearbox at this point for converting from the on-chip transport (such as ATB) into the data stream, and identifying the transition from idle to valid data one bit before the data is output is not difficult.

**Comment by IainCRobertson** [comment]
I'm still not totally sure I follow your concern.  

The benefit of including a null.alignment at the end if any run of idles is that it allows any run of idles that is long enough to function as a sync sequence for the data stream recipient, independent of any periodic sync scheduling mechanism.

In the expected/typical use case, at the point that the data stream is being generated (e.g. at the PIB driver), something is being sent every cycle (either packet data or idle).  In order to use null.alignment for the final idle byte just requires a pipeline register for the data that is the width of the output interface to give a 1 cycle lookahead.  This is neither costly nor complex.

If your concern is for idles inserted at source where there is also a 'valid' signal on the on-chip transport (which is supported even though it's unlikely to be used), then I agree that there could be an unknown number of cycles between sending an idle and sending something else, and in that case you can't easily know whether to insert null.alignment.  In that situation, just using null.idle is the right thing to do (leaving null.alignment insertion as the responsibility of the sink driver).  Let me see if I can come up with some words to cover this case.

**Comment by ved-rivos** [comment]
I expect synchronization to be done periodically even when there are idles. Now the specific concern I have is this:

> for unframed data streams, M consecutive null.idle packets directly followed by one null.alignment packet;

At start of cycle 0 I detect no packets, I insert a null.idle. AT start of second cycle I detect no packets, I insert a null.idle. At start of third cycle there is a packet to send. However this clause says that since I have sent 2 null.idle I need to insert a null.alignment. This is totally unnecessary. And I could not have inserted a null.alignment in cycle 2 since I have no premonition that says there will be a packet to send in the next cycle in future.

**Comment by IainCRobertson** [comment]
I agree about synchronization being periodic even in the presence of idles, but that doesn't mean you shouldn't be able to take advantage of a long idle run to start decoding data sooner if possible.

Why do you not think it acceptable to have a free-running data pipeline the width of the output?  This is cheap and simple to implement, and in all probability already exists for other reasons related to width conversion between input and output.  It adds a cycle of latency but gives you "lookahead" to the data for the next cycle, so you know when the 1st non-idle data is coming.  This is trivial to implement in my view.

**Comment by ved-rivos** [comment]
Then please add a non-normative note that this specification requires a 1 cycle delay line with a buffer to support insertion of the null.alignment as the last null in a idle sequence.

**Comment by ved-rivos** [comment]
But I think we are complicating it. The simplest change I think is to change section 2.2 line

from:
> A null packet is inserted in the data stream when there are no normal encapsulated packets to send.

to
> A null.idle packet is inserted in the data stream when there are no normal encapsulated packets to send.

**Comment by IainCRobertson** [comment]
I still think there's value in being able to take advantage of a long idle run as an opportunistic sync sequence.  I'm happy to make this behaviour optional though, and can word accordingly.

**Comment by IainCRobertson** [comment]
In principle, yes, though it's not always 31, hence the use of 'N'.  This isn't defined until the next section, but I'll play around with the wording and see what I can come up with.  I think we're aligned on the key points now.

**Comment by IainCRobertson** [comment]
Reopening as the changes resulting from this issue have introduced an undesireable side effect.

The outcome of this issue was to change the null packet definitions to allow the flow field to take any value, so that null packets originating at the trace source could be routed to a sink in the usual way.  This is fine for routing data over an internal trace infrastructure.  It's also fine for synchronizing to a byte stream, as the byte boundaries are known, and ignoring the flow bits in order to identify null packets is trivial.

However, it is not okay for synchronizing to a bit stream, where the byte boundaries are not known.  In this case, the synchronization is easy if null.idle is 0x00 and null.alignment is 0x80.  But if the flow bits can be non zero, it makes the synchronization detection vastly more complicated, because you have to start looking across multiple 8-bit groups for runs of 5 zeros (that might be the length fields).  This is not impossible but a vast an unnecessary additional complexity.

The solution is to add an additional sentence to state that when generating a bitstream, all null packets within the bitstream must have flow set to 0.
